Repository OpenDiablo2/OpenDiablo2, pull requests merged in 2019-11, with the labels that each got.

#103 Fixed MPQ load issue on french localized D2
  core/Engine.go
  mpq/MPQ.go
Labels: bug

#100 Adjust animation speed calculation.
  common/AnimatedEntity.go
Labels: bug

#102 mpq: implement GetFileList
  mpq/MPQ.go
Labels: enhancement

#106 core: rename mpq variable to archive to avoid confusion with mpq package
  core/Engine.go
Labels: enhancement

#111 Initial NPC support
  common/AnimatedEntity.go
  common/DataDictionary.go
  common/MonStats.go
  common/NPC.go
  common/Object.go
  common/Path.go
  core/Engine.go
  map/DS1.go
  map/Engine.go
  map/Region.go
  resourcepaths/ResourcePaths.go
Labels: enhancement

#112 Performance Enhancements
  common/Configuration.go
  common/Dcc.go
  common/StreamReader.go
  common/StreamReader_test.go
  common/TextDictionary.go
  core/Engine.go
  mpq/MPQStream.go
  tests/MPQ_test.go
  tests/MapLoad_test.go
Labels: enhancement

#115 More optimizations. Fixed button rendering issue.
  common/AnimatedEntity.go
  common/ColorConvert.go
  common/Dcc.go
  common/Sprite.go
  common/Weapons.go
  core/Engine.go
  go.sum
  mpq/MPQ.go
  tests/MapLoad_test.go
Labels: bug, enhancement

#118 Performance Enhancements
  common/Sprite.go
  go.mod
  go.sum
Labels: enhancement

#119 Test updates. MPQ file name changes.
  main.go
  mpq/MPQ.go
  tests/MPQ_test.go
Labels: bug

#120 More sprite optimizations
  common/Sprite.go
  core/Engine.go
  scenes/SelectHeroClass.go
Labels: enhancement

#123 Use delta time for scene updates.
  core/Engine.go
  main.go
  scenes/MapEngineTest.go
Labels: bug

#124 Vsync and FPS display toggles.
  core/Engine.go
  main.go
  scenes/MapEngineTest.go
Labels: enhancement

#125 Check if MPQ file was loaded before reading.
  core/Engine.go
Labels: enhancement

#126 common: generate atlas in y rather than x direction
  common/Sprite.go
Labels: bug

#127 Added support for all object layers.
  common/AnimatedEntity.go
  common/BitMuncher.go
  common/Cof.go
  common/Dcc.go
  common/NPC.go
  map/Region.go
Labels: enhancement

#107 common: use stringer and string2enum tools to convert back and forth …
  common/Cof.go
  common/animationmode_string.go
  common/weaponclass_string.go
  common/weaponclass_string2enum.go
Labels: enhancement

#108 common: convert objLookupRaw into a struct
  common/ObjectLookup.go
  core/Engine.go
Labels: enhancement

#83 Create run.sh
  run.sh
Labels: enhancement

#129 Improve run.sh
  run.sh
Labels: enhancement

#131 More optimizations and cleanup.
  d2common/DataDictionary.go
  d2common/d2enum/LayerStreamType.go
  d2core/Engine.go
  d2core/NPC.go
  d2core/d2scene/CharacterSelect.go
  d2core/d2scene/Credits.go
  d2core/d2scene/MainMenu.go
  d2core/d2scene/SelectHeroClass.go
  d2data/d2cof/COF.go
  d2data/d2cof/CofLayer.go
  d2data/d2datadict/LevelPresets.go
  d2data/d2dcc/CommonData.go
  d2data/d2dcc/DCC.go
  d2data/d2dcc/DCCCell.go
  d2data/d2dcc/DCCDirection.go
  d2data/d2dcc/DCCDirectionFrame.go
  d2data/d2dcc/DCCPixelBufferEntry.go
  d2data/d2ds1/CommonData.go
  d2data/d2ds1/DS1.go
  d2data/d2ds1/FloorShadowRecord.go
  d2data/d2ds1/SubstitutionGroup.go
  d2data/d2ds1/SubstitutionRecord.go
  d2data/d2ds1/TileRecord.go
  d2data/d2ds1/WallRecord.go
  d2data/d2dt1/Block.go
  d2data/d2dt1/DT1.go
  d2data/d2dt1/Tile.go
  d2render/AnimatedEntity.go
  d2render/Sprite.go
  d2render/d2mapengine/Region.go
  d2render/d2ui/Font.go
  d2render/d2ui/Manager.go
  main.go
  tests/MPQ_test.go
Labels: enhancement

#132 Added text entry. Fixed performance issue. Added error checking.
  d2core/d2scene/CharacterSelect.go
  d2core/d2scene/Credits.go
  d2core/d2scene/MainMenu.go
  d2core/d2scene/SelectHeroClass.go
  d2render/AnimatedEntity.go
  d2render/Sprite.go
  d2render/d2ui/Button.go
  d2render/d2ui/Label.go
  d2render/d2ui/TextBox.go
Labels: enhancement

#134 Renamed all files to proper go conventions.
  d2audio/audio_provider.go
  d2audio/sound_effect.go
  d2common/build_info.go
  d2common/d2enum/animation_frame.go
  d2common/d2enum/animation_mode.go
  d2common/d2enum/animation_mode_string.go
  d2common/d2enum/composite_type.go
  d2common/d2enum/draw_effect.go
  d2common/d2enum/hero_stance.go
  d2common/d2enum/layer_stream_type.go
  d2common/d2enum/palette_defs.go
  d2common/d2enum/weapon_class.go
  d2common/d2enum/weapon_class_string.go
  d2common/d2enum/weapon_class_string2enum.go
  d2common/d2interface/file_provider.go
  d2common/d2interface/scene_provider.go
  d2common/d2resource/resource_paths.go
  d2common/data_dictionary.go
  d2common/stream_reader.go
  d2common/stream_reader_test.go
  d2common/stream_writer.go
  d2common/stream_writer_test.go
  d2common/text_dictionary.go
  d2core/d2scene/blizzard_intro.go
  d2core/d2scene/character_select.go
  d2core/d2scene/main_menu.go
  d2core/d2scene/map_engine_testing.go
  d2core/d2scene/select_hero_class.go
  d2core/game_state.go
  d2data/animation_data.go
  d2data/d2datadict/level_presets.go
  d2data/d2datadict/level_types.go
  d2data/d2datadict/level_warp.go
  d2data/d2datadict/object_lookup.go
  d2data/d2datadict/object_types.go
  d2data/d2datadict/unique_items.go
  d2data/d2dcc/common_data.go
  d2data/d2dcc/dcc_cell.go
  d2data/d2dcc/dcc_direction.go
  d2data/d2dcc/dcc_direction_frame.go
  d2data/d2dcc/dcc_pixel_buffer_entry.go
  d2data/d2ds1/common_data.go
  d2data/d2ds1/floor_shadow_record.go
  d2data/d2ds1/substitution_group.go
  d2data/d2ds1/substitution_record.go
  d2data/d2mpq/crypto_buff.go
  d2data/d2mpq/mpq_file_record.go
  d2data/d2mpq/mpq_stream.go
  d2helper/color_convert.go
  d2render/animated_entity.go
Labels: enhancement

#136 Checkboxes!
  d2common/d2resource/resource_paths.go
  d2core/d2scene/select_hero_class.go
  d2render/d2ui/Checkbox.go
Labels: enhancement

#138 Fix checkboxes
  d2render/d2ui/checkbox.go
Labels: bug

#139 Another sprite optimization experiment.
  d2render/sprite.go
Labels: enhancement

#140 Fixed texture atlas. Added GC debugging.
  d2core/engine.go
  d2render/sprite.go
Labels: enhancement

#141 More sprite optimizations.
  .gitignore
  d2render/sprite.go
Labels: enhancement

#143 Added more functionality to character select screen.
  d2common/d2enum/hero.go
  d2common/d2enum/hero_string.go
  d2common/d2enum/hero_string2enum.go
  d2common/d2enum/region_id.go
  d2common/d2enum/region_layer.go
  d2common/d2resource/resource_paths.go
  d2common/stream_reader.go
  d2common/stream_writer.go
  d2common/stream_writer_test.go
  d2core/d2scene/character_select.go
  d2core/d2scene/game.go
  d2core/d2scene/main_menu.go
  d2core/d2scene/map_engine_testing.go
  d2core/d2scene/select_hero_class.go
  d2core/engine.go
  d2core/game_state.go
  d2core/npc.go
  d2data/d2compression/wav.go
  d2data/d2datadict/hero_objects.go
  d2render/animated_entity.go
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
  d2render/d2mapengine/tile_cache_record.go
  d2render/d2ui/button.go
  tests/mapload_test.go
Labels: enhancement

#144 fix permissions on .OpenDiablo2 directory
  d2core/game_state.go
Labels: bug

#152 Added the scrollbar.
  d2common/d2resource/resource_paths.go
  d2core/d2scene/character_select.go
  d2core/game_state.go
  d2render/d2ui/Scrollbar.go
Labels: enhancement

#153 Started work on gameplay scene.
  d2common/d2resource/resource_paths.go
  d2core/d2scene/character_select.go
  d2core/d2scene/game.go
  d2core/engine.go
  d2render/d2ui/font.go
  d2render/sprite.go
Labels: enhancement

#159 Additional credits in the credits screen #154
  CONTRIBUTORS
  d2core/d2scene/credits.go
Labels: enhancement

#161 Idle animation and hover gets out of sync
  d2core/d2scene/select_hero_class.go
Labels: bug

#162 Add map switcher
  d2core/d2scene/main_menu.go
  d2core/d2scene/map_engine_testing.go
  d2core/engine.go
  d2data/d2cof/cof.go
  d2data/d2dcc/dcc.go
  d2render/d2mapengine/region.go
Labels: enhancement

#164 Fixed crash on 0 animation speed entities.
  d2render/animated_entity.go
Labels: bug

#165 Place objects according to sub-cell
  d2render/animated_entity.go
Labels: bug

#167 Render to center of subtile
  d2render/animated_entity.go
Labels: bug

#177 Added inventory objects.
  d2common/d2enum/hero.go
  d2common/d2enum/inventory_item_type.go
  d2common/d2interface/inventory_item.go
  d2core/character_equipment.go
  d2core/d2scene/character_select.go
  d2core/engine.go
  d2core/game_state.go
  d2core/hero.go
  d2core/hero_objects.go
  d2core/inventory_item_armor.go
  d2core/iventory_item_weapon.go
  d2core/npc.go
  d2data/d2datadict/hero_objects.go
  d2render/animated_entity.go
  d2render/d2mapengine/region.go
Labels: enhancement

#178 Closes Issue#176
  d2core/d2scene/credits.go
Labels: bug

#172 Toggle tile display in map test with F7
  d2core/d2scene/map_engine_testing.go
  d2render/d2mapengine/engine.go
Labels: enhancement

#169 Render in two passes
  d2render/d2mapengine/engine.go
Labels: enhancement

#179 Render loop with two passes
  d2render/d2mapengine/engine.go
Labels: enhancement

#180 Performance improvements
  d2data/d2dcc/dcc_direction.go
  d2data/d2dcc/dcc_pixel_buffer_entry.go
  d2helper/timeutils.go
  d2render/animated_entity.go
  d2render/sprite.go
  go.mod
  go.sum
Labels: enhancement

#181 Fix animation issue and map layer rendering.
  d2render/d2mapengine/engine.go
  d2render/sprite.go
Labels: bug

#182 Adjust sub-tile rendering offset.
  d2render/animated_entity.go
Labels: bug

#185 Switch items to dynamic load with a common struct, add misc.txt loading
  d2common/calcstring.go
  d2core/engine.go
  d2data/d2datadict/armor.go
  d2data/d2datadict/item_common.go
  d2data/d2datadict/map_helper.go
  d2data/d2datadict/misc.go
  d2data/d2datadict/missiles.go
  d2data/d2datadict/unique_items.go
  d2data/d2datadict/weapons.go
Labels: enhancement

#191 Visual Studio Code extension recommendations
  .gitignore
  .vscode/extensions.json
  README.md
Labels: enhancement

#192 Update Ebiten Reference
  go.mod
  go.sum
Labels: enhancement

#193 Fix issues with rendering order
  d2render/d2mapengine/engine.go
Labels: enhancement

#194 Remove texture atlass
  d2render/sprite.go
Labels: enhancement

#173 Switcher with presets & better tiles randomizing
  d2core/d2scene/main_menu.go
  d2core/d2scene/map_engine_testing.go
  d2render/animated_entity.go
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
  go.mod
  main.go
Labels: enhancement

#196 Phase 1 prep work for gameplay
  d2core/d2scene/game.go
  d2core/d2scene/map_engine_testing.go
  d2render/animated_entity.go
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
  go.mod
  go.sum
  main.go
  tests/mapload_test.go
  tests/mpq_test.go
Labels: enhancement

#198 Finished orientation values.
  d2core/d2scene/game.go
  d2render/animated_entity.go
Labels: enhancement

#200 Create tiles cache on region loading
  d2core/d2scene/map_engine_testing.go
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
Labels: enhancement

#202 Minor enhancements to map loading
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
  d2render/d2mapengine/tile_cache_record.go
  d2render/sprite.go
  go.mod
  go.sum
Labels: enhancement

#203 More map engine improvements.
  d2core/d2scene/map_engine_testing.go
  d2render/animated_entity.go
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
Labels: enhancement

#206 Prevent some map load crashes.
  d2render/animated_entity.go
  d2render/d2mapengine/region.go
Labels: bug

#208 Map Test: Fix the tile coordinates shown in the top left
  d2core/d2scene/map_engine_testing.go
Labels: bug

#209 Increase draw distance up and down
  d2core/d2scene/map_engine_testing.go
  d2render/d2mapengine/engine.go
Labels: bug

#211 Random tiles
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
Labels: bug

#214 Updated module references.
  go.mod
  go.sum
Labels: enhancement

#219 Fix GetTiles being called for already cached tiles.
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
  go.mod
  go.sum
Labels: enhancement

#220 Changing the terminology of tile components.
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
  go.mod
  go.sum
Labels: enhancement

#228 Switch to using the TileType type for tiles.
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
  go.mod
  go.sum
Labels: enhancement

#229 Update d2shared reference
  go.mod
  go.sum
Labels: enhancement

#230 Only render visible regions
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
Labels: enhancement

#232 Animate floor tiles
  d2render/d2mapengine/engine.go
  d2render/d2mapengine/region.go
  go.mod
  go.sum
Labels: enhancement
